apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-service-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "true"
spec:
  ingressClassName: "gce"
  rules:
  - http:  # Start without host - access via IP
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-service-service
            port:
              number: 80