apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb-container
          image: mysql:8  # ✅ Use standard MySQL image
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: MYSQL_DATABASE
              value: demo_db
          volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
          - name: init-script  # Add init script
            mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          # Add readiness probe
          readinessProbe:
            exec:
              command:
              - mysqladmin
              - ping
              - -h
              - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
          # Add liveness probe
          livenessProbe:
            exec:
              command:
              - mysqladmin
              - ping
              - -h
              - localhost
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: init-script  # Add init script volume
        configMap:
          name: mysql-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS demo_db;
    USE demo_db;
    
    CREATE TABLE IF NOT EXISTS customer_details (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    INSERT IGNORE INTO customer_details (first_name, last_name, email, phone) VALUES
    ('Amit', 'Sharma', 'amit.sharma@example.com', '9876543210'),
    ('Priya', 'Verma', 'priya.verma@example.com', '9876501234'),
    ('Rohan', 'Mehta', 'rohan.mehta@example.com', '9867123456'),
    ('Neha', 'Kapoor', 'neha.kapoor@example.com', '9856123478'),
    ('Arjun', 'Singh', 'arjun.singh@example.com', '9845236789'),
    ('Kavita', 'Jain', 'kavita.jain@example.com', '9834567890'),
    ('Sahil', 'Gupta', 'sahil.gupta@example.com', '9823456789'),
    ('Meera', 'Joshi', 'meera.joshi@example.com', '9812345678'),
    ('Vikas', 'Nair', 'vikas.nair@example.com', '9801234567'),
    ('Ananya', 'Reddy', 'ananya.reddy@example.com', '9790123456');
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
spec:
  selector:
    app: mysqldb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
