apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service-container
        image: chiragkohli29/api-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "mysqldb-service"  # name of the DB service
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "yourpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service-service
spec:
  selector:
    app: api-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
