apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: customer-api-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: customer-api.local  # Change this to your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: customer-api-service
            port:
              number: 80
  # Uncomment below for TLS
  # tls:
  # - hosts:
  #   - customer-api.local
  #   secretName: customer-api-tls