apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynodeapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynodeapp
  template:
    metadata:
      labels:
        app: mynodeapp
    spec:
      containers:
      - name: mynodeapp-container
        image: chiragkohli29/mynodeapp:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "mysqldb-service"  # name of the DB service
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "yourpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: mynodeapp-service
spec:
  selector:
    app: mynodeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
