apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqldb
  template:
    metadata:
      labels:
        app: sqldb
    spec:
      containers:
      - name: sqldb-container
        image: chiragkohli29/sqldb:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD_FILE
          value: "/run/secrets/mysql-root-password"
        - name: MYSQL_DATABASE
          value: "demo_db"
        volumeMounts:
        - name: mysql-secret
          mountPath: "/run/secrets"
          readOnly: true
      volumes:
      - name: mysql-secret
        secret:
          secretName: mysql-secret
---
apiVersion: v1
kind: Service
metadata:
  name: sqldb-service
spec:
  selector:
    app: sqldb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
